spring:
  application:
    name: peer2
server:
  port: 8862

eureka:
  instance:
    hostname: peer2         # 指定该Eureka实例的主机名
#    ip-address: 192.168.1.2
#    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:8761/eureka/
#  server:
#    enable-self-preservation: false
